# Generated by Django 4.2.2 on 2023-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='popularity',
            new_name='rooms_count',
        ),
        migrations.AddField(
            model_name='room',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
