# Generated by Django 4.2.2 on 2023-07-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_about_profile_bio_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', upload_to='images/'),
        ),
    ]
