# Generated by Django 4.2.2 on 2023-07-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
